<?php

namespace AppBundle\Repository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatest10()
    {
        $dql = "SELECT n FROM AppBundle:News n ORDER BY n.createdAt DESC";

        $q = $this->_em->createQuery($dql);
        $q->setMaxResults(10);

        return $q->getResult();
    }
}
