# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    app.unique_email_address_validator:
        class: AppBundle\Validator\UniqueEmailAddressValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator }

    app.file_manager:
        class: AppBundle\Service\FileManager\FileManager
        arguments:
            - "@service_container"
            - "@request_stack"

    app.app_twig_extension:
        class: AppBundle\Twig\Extension\AppExtension
        arguments: ["@app.file_manager"]
        tags:
            - { name: twig.extension }

    app.news_voter:
        class: AppBundle\Security\NewsVoter
        public: false
        tags:
            - { name: security.voter }
